"""notification upgrade

Revision ID: c196149fe6e4
Revises: d30ad96b790c
Create Date: 2025-02-26 21:51:51.248288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c196149fe6e4'
down_revision: Union[str, None] = 'd30ad96b790c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('job_id', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_notifications_job_id'), 'notifications', ['job_id'], unique=True)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_job_id'), table_name='notifications')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'job_id')
    # ### end Alembic commands ###
